from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class PriceDataProvider(Protocol):
    def get_ohlcv(self, ticker: str, interval: str, start: str, end: str) -> list[dict[str, Any]]: ...
    def get_latest_price(self, ticker: str) -> dict[str, Any]: ...
    def ping(self) -> bool: ...
